export type Application = {
  id: number;
  연도: number | string;
  군: string;
  대학: string;
  학과: string;
  합불: string;
  내신: number | null;
  국어선택: string | null;
  국어백분위: number | null;
  수학선택: string | null;
  수학백분위: number | null;
  탐구1과목: string | null;
  탐구1백분위: number | null;
  탐구2과목: string | null;
  탐구2백분위: number | null;
  영어등급: number | null;
  한국사등급: number | null;
  백분위합: number | null;
  표준점수합: number | null;
};
